config/routes.rb
Rails.application.routes.draw do
  get 'replies/index'
  get 'replies/show'
  get 'replies/edit'
  get 'replies/new'
  root 'homes#index'
  devise_for :students, controllers: { registrations: 'students/registrations' }
  resources :students, :only => [:index]
  devise_scope :student do  
    get '/students/sign_out' => 'devise/sessions#destroy'     
 end
 resources :courses
 resources :registered_courses
 resources :questions
 resources :replies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
    validates :name, :presence=> true, :uniqueness => true
    
    has_many :registered_courses
    has_many :students, through: :registered_courses, :dependent => :destroy
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :replies
    has_many :students, through: :replies, :dependent=> :destroy
end

app/models/registered_course.rb
class RegisteredCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :student
  belongs_to :question
end

app/models/student.rb
class Student < ApplicationRecord
  validates :email, :name, presence: true
  validates :roll_no, uniqueness: true
  # Relation with courses through registered courses
  has_many :registered_courses
  has_many :courses, through: :registered_courses, :dependent => :destroy
  # Relation with replies through questions
  has_many :replies
  has_many :questions, through: :replies, :dependent=> :destroy
  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable, :timeoutable

         enum role: { admin: 0, student: 1 } 
         after_initialize :set_default_role, :if =>  :new_record?
         def set_default_role
          self.role ||= :student
        end
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :roll_no, :role, :email, :password, :password_confirmation)}

               devise_parameter_sanitizer.permit(:account_update, keys: [:name, :roll_no, :email,
                questions_attributes: [
                    :id,
                    :question,
                    :_destroy
               ]])


          end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_student!
  before_action :course_find, only:[:show, :edit, :update, :destroy]
  def index
    @courses = Course.all
    @st_courses = current_student.courses
    @res_courses = current_student.registered_courses

  end

  
  def show
  end

       
   def new
    @course = Course.new
  end


  def create
    @course = Course.new(course_params)
    respond_to do |format|
      if @course.save
        format.js
       format.html { redirect_to courses_path}
       format.json { render :index, status: :created, location: @course }
      else
        format.js
       format.html { render :new }
       format.json { render json: @course.errors, status: :unprocessable_entity }
     end
    end
   
  end


  def edit
  end


  def update
    if @course.update(course_params)
      redirect_to courses_path
    else
      render :new, notice: 'course was not updated.'
    end
  end


  def destroy
        if @course.destroy
      redirect_to courses_path
    else    	
    end
  end
  

    private 
    def course_find 
      @course = Course.find(params[:id])
    end
    def course_params 
    params.require(:course).permit(:name, :age, :status, :email, :password)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @reply = @question.replies.new
    @all_replies = @question.replies
   
  end
  def edit

  
  end

  def new
  end


end

app/controllers/registered_courses_controller.rb
class RegisteredCoursesController < ApplicationController
  before_action :registered_course_find, only:[:edit, :update]

  def index
    @registered_courses= RegisteredCourse.where(student_id: params[:id])
  end

  def show
    @grades = current_student.registered_courses.find_by(course_id: params[:id])
  end

  def new
    @rc = RegisteredCourse.new
  end

  def create 
    if current_student.role == "student"
      @rc = RegisteredCourse.create(student_id: params[:student_id], course_id: params[:course_id], grade: "")
      redirect_to courses_path
    else
      puts "your are admin"
    end
    
  end
  
  def edit
    
    
  end
  
  def update
      if @rc.update(rc_params)
        flash[:success] = "Register course was successfully updated"
        redirect_to students_path
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end
  
  private 
  def registered_course_find 
    @rc = RegisteredCourse.find(params[:id])
  end
  def rc_params
    params.require(:registered_course).permit(:grade)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def index
  end

  def show
    @replies = Reply.where(question_id: params[:id])
    @question = Question.find(params[:id])
  end

  def edit
  end

  def new
    
  end
  def create 
    @reply = Reply.new(reply_params)
    respond_to do |format|
      if @reply.save
        format.js
      else
        format.js
        render :'new'
      end
    end
  end
  private
  def reply_params
    params.require(:reply).permit(:reply, :student_id, :question_id)
  end
end

app/controllers/students/registrations_controller.rb
class Students::RegistrationsController < Devise::RegistrationsController


  def edit
    resource.questions.build

  end
  protected

 
    def update_resource(resource, params)

    # Require current password if user is trying to change password.
    return super if params["password"]&.present?

    # Allows user to update registration information without password.
    resource.update_without_password(params.except("current_password"))
  end

  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index 
        @students = Student.where(role: true)
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/registered_courses_helper.rb
module RegisteredCoursesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.html.erb
<%= form_for @course, remote: true do |f| %>
<%= f.label :Name%>
<%= f.text_field :name%><br>     
<%=f.submit "Search", class: "search-btn"%>
    <% end %>

app/views/courses/create.js.erb
<% if @course.errors.any? %>
    alert('Please enter course name! ');
<% else %>
<% end %>

app/views/courses/edit.html.erb
<h1>Courses#edit</h1>
<p>Find me in app/views/courses/edit.html.erb</p>

app/views/courses/index.html.erb
<!-- Nav bar -->
<%= render 'homes/navbar' %>
<!-- Index page starting for here-->
<div class="container mt-5">
   <% if current_student.role == "student"%>
   <!-- Section for registered courses -->
   <div class="accordion accordion-flush" id="accordionFlushExample">
   <div class="accordion-item">
      <h2 class="accordion-header" id="flush-headingOne">
         <button class="accordion-button collapsed border border-dark" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
         CLICK TO VIEW YOUR REGISTER COURSES
         </button>
      </h2>
      <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
         <div class="accordion-body">
            <table class="table table-bordered text-center">
               <tr>
                  <th>Course</th>   
                  <th>Grade</th>
               </tr>
               <% @st_courses.each do |st_co|%>
               <tr>
                  <td><%= st_co.name.capitalize%></td>
                  <td>
                     <%= link_to 'View Grade', registered_course_path(st_co), class: "btn btn-info" %> 
                  </td>
               </tr>
               <% end %>
            </table>
         </div>
         <br><br>
      </div>
      </div>
   </div>
   <!-- Section for All courses -->
   <table class="table table-bordered text-center">
      <h4>ALL COURSES</h4>
      <br>
      <tr>
         <th>Course</th>
         <th colspan=2>Click To Register</th>
      </tr>
      <% @courses.each do |c|%>
      <tr>
         <td><%= c.name%></td>
         <td colspan=2>
            <% if current_student.courses.include? c  %>
               <span class= "text-secondary">Registered</span>
            <% else %>
               <%= link_to 'Register Now', registered_courses_path(course_id: c.id, student_id: current_student.id), method: :post, class: "btn btn-info", data: { confirm: 'Are you sure?' }%>
            <% end %>
         </td>
      </tr>
      <% end %>
   </table>
   <% else %>
   <%= link_to 'ADD NEW COURSE', new_course_path, class: "btn btn-primary" %> <br><br>
   <table class="table table-bordered">
      <tr>
         <th>Name</th>
         <th colspan=2>Actions</th>
      </tr>
      <% @courses.each do |c|%>
      <tr>
         <td><%= c.name%></td>
         <td>
            <ul class="list-group list-group-flush">
               <li class="list-group-item"><%= link_to 'Edit', edit_course_path(c), class: "btn btn-info" %></li>
               <li class="list-group-item"><%= button_to 'Delete',  c , method: :delete, class: "btn btn-danger btn-sm",data: {confirm: "Are you sure?"} %></li>
            </ul>
         </td>
      </tr>
      <% end %>
   </table>
   <% end %>
</div>

app/views/courses/new.html.erb
<%= render 'homes/navbar' %>
<%= render 'form' %>

app/views/courses/show.html.erb
<h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p>

app/views/homes/_navbar.html.erb
<% if student_signed_in? %>
  <% if current_student.role == "admin" %>
    <ul class="nav nav-pills mt-3">
    <li class="nav-item">
        <%= link_to "#{current_student.name}", root_path ,class: "nav-link text-uppercase text-secondary"%>
    </li>
    <li class="nav-item">
        <button class=" nav-link btn btn-primary position-relative pt-0">
        <%= link_to 'Courses', courses_path ,class: "nav-link"%>
        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
        <%= Course.count%>
        <span class="visually-hidden"></span>
        </span>
        </button>
    </li>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <li class="nav-item">
        <button class=" nav-link btn btn-primary position-relative pt-0">
        <%= link_to 'Students', students_path ,class: "nav-link"%>
        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
        <%= Student.count-1%>
        <span class="visually-hidden"></span>
        </span>
        </button>
    </li>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <li class="nav-item">
        <%= link_to 'Edit Profile', edit_student_registration_path, class: "nav-link"%>
    </li>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <li class="nav-item">
        <%= link_to 'All Questions', questions_path, class: "nav-link"%>
    </li>
    <li class="nav-item" style="margin-left:54%">
        <%= link_to 'logout', destroy_student_session_path, class: "nav-link"%>
    </li>
    </ul>
  <% else %>
    <ul class="nav nav-pills mt-3">
    <li class="nav-item">
        <a class="nav-link disabled "><%= current_student.name.capitalize%></a>
    </li>
    <li class="nav-item">
        <button class=" nav-link btn btn-primary position-relative pt-0">
        <%= link_to 'Courses', courses_path ,class: "nav-link"%>
        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
        <%= Course.count%>
        <span class="visually-hidden"></span>
        </span>
        </button>
    </li>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <li class="nav-item">
        <%= link_to 'Edit Profile', edit_student_registration_path, class: "nav-link"%>
    </li>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <li class="nav-item">
        <%= link_to "#{current_student.name.capitalize}'s Questions", question_path(current_student), class: "nav-link"%>
    </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <li class="nav-item">
        <%= link_to 'All Questions', questions_path, class: "nav-link"%>
    </li>
    <li class="nav-item" style="margin-left:54%">
        <%= link_to 'logout', destroy_student_session_path%>
    </li>
    </ul>
  <% end %>
<% else %>
  <ul class="nav nav-pills">
    <li class="nav-item">
      <a class="nav-link">Stranger</a>
    </li>
    <li class="nav-item" style="margin-left:79%">
      <%= link_to 'Sign up', new_student_registration_path, class: "nav-link"%>
    </li>
      <li class="nav-item">
      <%= link_to 'Sign in', new_student_session_path, class: "nav-link"%>
    </li>
  </ul>
<% end %>

app/views/homes/index.html.erb
<%= render 'navbar' %>

app/views/questions/_show.html.erb
<div class="container mt-5">
<strong>Question: <%= @question.question.capitalize+" ?"%></strong><br>
<strong>Your Replies: </strong>
            <% @all_replies.each do |replies|%>
        <ol>
            <li><%= replies.reply%></li>
        </ol>
            <% end %>
<%= render 'replies/form'%>
</div>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

app/views/questions/index.html.erb
<%= render 'homes/navbar' %>
<div class="container mt-5">
    <h4>ALL QUESTION</h4><br>
<% if current_student.role == "admin"%>
    <table class="table table-bordered">
        <tr>
            <th>Id</th>
            <th>Question</th>
            <th>Replies</th>
        </tr>
        <% @questions.each do |q|%>
        <tr>
            <td><%= q.id%></td>
            <td><%= q.question%></td>
            <td><%= link_to 'View All Reply', reply_path(q) ,class: 'btn btn-outline-primary'%></td>
        </tr>
        <% end %>
    </table>
<% else %>
    <table class="table table-bordered">
        <tr>
            <th>Id</th>
            <th>Question</th>
            <th>Actions</th>
        </tr>
        <% @questions.each do |q|%>
        <tr>
            <td><%= q.id%></td>
            <td><%= q.question%></td>
            <td><%= link_to 'Reply', question_path(q) ,class: 'btn btn-outline-success', remote: true%>
        </tr>
        <% end %>
    </table>
    <div class="here">
    </div>
<% end %>
</div>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>

app/views/questions/show.html.erb
<%= render 'homes/navbar' %>

app/views/questions/show.js.erb
$(".here").html('<%= escape_javascript render ('show')%>');

app/views/registered_courses/_form.html.erb
<%= form_for @rc do |f|%>
<div class="modal-body">
    <%= f.label :grade%>
    <%= f.text_field :grade%><br>
    
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= f.submit%>
</div>
<% end %>

app/views/registered_courses/_show.html.erb
<div class="modal-body">
    <div class="container-fluid m-3">
        
        <p>Your grades : 
            <strong>
            <% if @grades.grade.present?%>
                <%= @grades.grade%>
            <% elsif %>
            you have not graded yet!    
            <% end %>
            </strong
        ></p>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
</div>

app/views/registered_courses/edit.html.erb
<%= render 'homes/navbar' %>
<%= render 'form' %>

app/views/registered_courses/edit.js.erb
$("p").html('<%= j render(:partial => 'form') %>');

app/views/registered_courses/index.html.erb
<%= render 'homes/navbar' %>
<div class="container mt-5">
    <h4>REGISTERED COURSES GRADES</h4><br>
    <table class="table table-bordered">
        <tr>
            <th>Name</th>
            <th>Grade</th>
        </tr>
        <% @registered_courses.each do |reg|%>
        <tr>
            <td>
                <%= reg.course.name%>
            <td>
                <% if reg.grade%>
                <%= reg.grade%>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Edit', edit_registered_course_path(reg), class: "btn btn-info btn-sm", data: {bs_toggle: "modal", bs_target: "#edit", remote: true} %>
                <% else %>
                <strong>You aren't graded yet!</strong>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Edit', edit_registered_course_path(reg), class: "btn btn-info", data: {bs_toggle: "modal", bs_target: "#edit", remote: true} %>
                <% end %>
            </td>
        </tr>
        <% end %>
    </table>
</div>

<!-- Modal -->
<div class="modal fade" id="edit" tabindex="-1" aria-labelledby="editLabel" aria-hidden="true" role="document">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editLabel">Edit Gardes</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <p id="editForm">
      </p>     
    </div>
  </div>
</div>

app/views/registered_courses/show.html.erb
<div class="container-fluid m-3">
    
    <p>Your grades : 
        <strong>
        <% if @grades.grade.present?%>
            <%= @grades.grade%>
        <% elsif %>
        you have not graded yet!    
        <% end %>
        </strong
    ></p>
</div>

app/views/replies/_form.html.erb
<%= simple_form_for @reply, remote: true do |f|%>
<%= f.input :reply, label: 'Create new reply: '%>
<%= f.input :student_id, as: :hidden,input_html: {value: "#{current_student.id}"}%>
<%= f.input :question_id, as: :hidden,input_html: {value: "#{@question.id}"}%>

<%= f.submit%>
<% end %>

app/views/replies/create.js.erb
<% if @reply.errors.any? %>
<% @reply.errors.each do |e|%>
alert('<%= e.message%>');
<% end %>
<% else %>


<% end %>

app/views/replies/edit.html.erb
<h1>Replies#edit</h1>
<p>Find me in app/views/replies/edit.html.erb</p>

app/views/replies/index.html.erb
<h1>Replies#index</h1>
<p>Find me in app/views/replies/index.html.erb</p>

app/views/replies/new.html.erb
<%= render 'form' %>

app/views/replies/show.html.erb
<%= render 'homes/navbar' %>
<div class="container mt-5">
    <h3>Question: <%= @question.question.capitalize+ " ."%></h3><br>

        <% @replies.each do |replies|%>
    <ul>
        <% if replies.present?%>
        <li><%= replies.reply%>
            <span class="float-end">Student Name: <%= replies.student.name%></span>
        </li>
        <hr>
        <% else %>
        <% end %>
    </ul>
        <% end %>
</div>

app/views/students/index.html.erb
<%= render 'homes/navbar' %>
<div class="container mt-5">
    <h4>ALL STUDENTS</h4><br>
    <table class="table table-bordered">
        <tr>
            <th>Roll #</th>
            <th>Name</th>
            <th>Email</th>
            <th>Register courses</th>
        </tr>
        <% @students.each do |s|%>
        <tr>
            <td><%= s.roll_no%></td>
            <td><%= s.name%></td>
            <td><%= s.email%></td>
            <td>
                <%= link_to 'Register Courses', registered_courses_path(id: s.id),class: "btn btn-info"%>
            </td>
            
        </tr>
        <% end %>
    </table>
</div>